FROM rockylinux:9

USER root

# essential packages
RUN dnf install -y dnf-plugins-core git-core sudo zsh \
    && dnf clean all \
    && rm -rf /var/cache/yum

# Add user with the expected ID (automated setup does not work atm)
RUN useradd -l -u 1000 -G wheel -md /home/gbraad -s /usr/bin/zsh -p gbraad gbraad \
    && sed -i.bkp -e 's/%wheel\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%wheel ALL=NOPASSWD:ALL/g' /etc/sudoers

# install tailscale
RUN dnf config-manager --add-repo https://pkgs.tailscale.com/stable/rhel/9/tailscale.repo \
    && dnf install -y \
        tailscale \
    && dnf clean all \
    && rm -rf /var/cache/yum

RUN dnf install -y \
        epel-release \
    && dnf install -y \
        stow

RUN dnf install -y \
        mc vim tmux screen links lynx \
    && dnf clean all \
    && rm -rf /var/cache/yum

# powerline
RUN dnf install -y \
        powerline vim-powerline tmux-powerline \
    && dnf clean all \
    && rm -rf /var/cache/yum

RUN dnf install -y \
        openssh-server \
    && dnf clean all \
    && rm -rf /var/cache/yum

RUN dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo \
    && dnf install -y \
       gh \
    && dnf clean all \
    && rm -rf /var/cache/yum

COPY scripts/tailscaled /etc/init.d/tailscaled
RUN mkdir -p /var/run/tailscale /var/cache/tailscale /var/lib/tailscale

USER gbraad